language: python
sudo: false

python:
- "3.6"

#directory that contains the source md
env:
- DN_DOCS_DIR=pages

#html -> directory that contains the compiled hml
script:
    - docnado --html docs --nav_limit taskbutler,bashblog,admindojo


deploy:
  fqdn: slashlog.org
  provider: pages
  skip-cleanup: true
  local-dir: docs
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master