language: python
sudo: false

python:
- "3.6"


script:
    - docnado --html docs --nav_limit taskbutler

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: docs
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master